### PR TITLE
Fix/router

### PR DESCRIPTION
**Pull request by samuelbeard**

### CODE REVIEW

**Comment by samuelbeard** [comment]
I've just noticed that you have submitted a PR with a similar aim... We will have to review both and combine.

**Comment by samuelbeard** [comment]
I added some of your changes to my PR.

**Comment by samuelbeard** [comment]
Verbose structure and to be prepared if that file gets maaasssiivvee.

If we have all of the routes and any other context functions and stuff in the same file, it will get really but and messy. Keeping them out makes it easy to see all the pages at once and structure them nicely. I'm used to doing it that way from other frameworks I've used over the years too lol.

**Comment by Maximilian118** [comment]
Fair enough.

**Pull request merged**
